### ISSUE TITLE
failed to load models in repository

### ISSUE THREAD

**Issue by jjburred** [pc2752/percussive_synth#2]
When trying to load one of the models provided with the repository, it fails with an 'Read less bytes than requested' error.

It works, however, when downloading the models from the Google Drive link included in the README, but they seem to be older (oct 2019 vs april 2020).

Maybe you could commit the correct models to the repository, or otherwise change the default model configuration in order for the provided generation code example to work with the newer model files? thanks

**Comment by aframires** [comment]
Hello!

Thank you very much for your feedback!

As an initial approach, we tried the Github Large File Storage for this. However, it has a limited bandwidth and therefore, we did not use them any longer. 

I should have already removed the link to the LFS.

I would be very happy if you could handle that and propose a pull request. I believe it would consist of 2 simples tasks:

1. Cleaning the dependency to the LFS
2. Add a function which downloads the model from Drive and stores them where they should be. In the Google Colab notebook, I already handled this. You can take a look at: https://colab.research.google.com/drive/1NHZjbzBNNg_5F3xZbuLXlxRt5k-aFnwf

Best regards,
António
